#
# Check
# https://circleci.com/docs/2.0/language-python/ for more details
# https://circleci.com/docs/2.0/configuration-reference/#orbs-requires-version-21
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.8
      # maybe need, but how to add it: --cap-add=SYS_ADMIN
      #- image: ubuntu:18.04

    steps:
      - checkout
      #- run: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config
            sudo apt-get install -y wget
            sudo apt-get install -y libarchive-dev

      - run:
          name: Install Singularity
          #v2. wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
          #cd singularity-$VER
          command: |
            VER=3.6.4
            wget https://github.com/hpcng/singularity/releases/download/v$VER/singularity-$VER.tar.gz
            tar xvf singularity-$VER.tar.gz
            cd singularity
            ./configure --prefix=/usr/local --sysconfdir=/etc
            make
            sudo make install

      - run:
          name: test image
          command: |
            source ~/.bashrc
            singularity pull --name scrnaseq.sif shub://togop/singularity_recipes:r-scrnaseq
            singularity exec scrnaseq.sif R -e 'print("hello world")'
            singularity exec scrnaseq.sif R -e 'library(SingleR)'
            singularity exec scrnaseq.sif R -e 'library(Seurat)'
