#
# Check
# https://circleci.com/docs/2.0/language-python/ for more details
# https://circleci.com/docs/2.0/configuration-reference/#orbs-requires-version-21
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.8
      # maybe need, but how to add it: --cap-add=SYS_ADMIN
      #- image: ubuntu:18.04

    steps:
      - checkout
      #- run: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config
            sudo apt-get install -y wget
            sudo apt-get install -y libarchive-dev

      - run:
          name: Install Go & Singularity
          #- run:
          #    name: Install Singularity
          #    command: |
          #      source ~/.bashrc
          command: |
            export GO_VER=1.16.2 OS=linux ARCH=amd64  # Replace the values as needed
            wget https://dl.google.com/go/go$GO_VER.$OS-$ARCH.tar.gz # Downloads the required Go package
            sudo tar -C /usr/local -xzvf go$GO_VER.$OS-$ARCH.tar.gz # Extracts the archive
            rm go$GO_VER.$OS-$ARCH.tar.gz    # Deletes the ``tar`` file
            export PATH=/usr/local/go/bin:$PATH
            echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bashrc
            export GOPATH=/usr/local/go
            echo 'export GOPATH=/usr/local/go' >> ~/.bashrc
            source ~/.bashrc
            echo "GOPATH=${GOPATH}"
            sudo mkdir -p ${GOPATH}/src/github.com/sylabs
            cd ${GOPATH}/src/github.com/sylabs

            export VERSION=3.7.2 # adjust this as necessary
            sudo wget https://github.com/hpcng/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
            sudo tar -xzf singularity-${VERSION}.tar.gz
            sudo cd singularity
            sudo ./mconfig
            sudo make -C builddir
            sudo make -C builddir install
            singularity version

          #VER=2.5.2
          #wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
          #tar xvf singularity-$VER.tar.gz
          #cd singularity-$VER
          #./configure --prefix=/usr/local --sysconfdir=/etc
          #make
          #sudo make install

      - run:
          name: test image
          command: |
            source ~/.bashrc
            singularity pull --name scrnaseq.sif shub://togop/singularity_recipes:r-scrnaseq
            singularity exec scrnaseq.sif R -e 'print("hello world")'
            singularity exec scrnaseq.sif R -e 'library(SingleR)'
            singularity exec scrnaseq.sif R -e 'library(Seurat)'
