#
# Check
# https://circleci.com/docs/2.0/language-python/ for more details
# https://circleci.com/docs/2.0/configuration-reference/#orbs-requires-version-21
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.8
      #- image: ubuntu:18.04

    steps:
      - checkout
      #- run: apt-get install -y sudo # https://discuss.circleci.com/t/sudo-command-not-found/14208/4
      #- run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      #- run: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config
            sudo apt-get install -y wget libarchive-devel

      - run:
          name: Install Singularity
          command: |
            VER=2.5.2
            wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
            tar xvf singularity-$VER.tar.gz
            cd singularity-$VER
            ./configure --prefix=/usr/local --sysconfdir=/etc
            make
            sudo make install

      - run:
          name: test image
          command: |
            source ~/.bashrc
            singularity pull --name scrnaseq.sif shub://togop/singularity_recipes:r-scrnaseq
