#
# Check
# https://circleci.com/docs/2.0/language-python/ for more details
# https://circleci.com/docs/2.0/configuration-reference/#orbs-requires-version-21
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.8

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config
            sudo apt-get install -y wget
            sudo apt-get install -y libarchive-dev

      - run:
          name: Install Go & Singularity 3
          command: |
            export GO_VER=1.16.2 OS=linux ARCH=amd64  # Replace the values as needed
            wget https://dl.google.com/go/go$GO_VER.$OS-$ARCH.tar.gz # Downloads the required Go package
            sudo tar -C /usr/local -xzvf go$GO_VER.$OS-$ARCH.tar.gz # Extracts the archive
            rm go$GO_VER.$OS-$ARCH.tar.gz    # Deletes the ``tar`` file
            export GOROOT=/usr/local/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

            echo 'export GOROOT=/usr/local/go' >> ~/.bashrc
            echo 'export GOPATH=$HOME/go' >> ~/.bashrc
            echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.bashrc

            source ~/.bashrc
            echo "GOPATH=${GOPATH}"
            mkdir -p ${GOPATH}/src/github.com/sylabs
            cd ${GOPATH}/src/github.com/sylabs

            export VERSION=3.7.2 # adjust this as necessary
            wget https://github.com/hpcng/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
            tar -xzf singularity-${VERSION}.tar.gz
            cd singularity
            ./mconfig --without-suid
            make -C builddir
            sudo make -C builddir install

#      - run:
#          name: Install Singularity 2
#          command: |
#            VER=2.5.2
#            wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
#            tar xvf singularity-$VER.tar.gz
#            cd singularity-$VER
#            ./configure --prefix=/usr/local --sysconfdir=/etc
#            make
#            sudo make install

      - run:
          name: Test system
          command: |
            source ~/.bashrc
            python --version
            go version
            singularity version

      - run:
          name: Test scrnaseq image
          command: |
            source ~/.bashrc
            sudo singularity pull --name scrnaseq.sif shub://togop/singularity_recipes:r-scrnaseq
            singularity exec scrnaseq.sif R --version
            singularity exec scrnaseq.sif R -e 'print("hello world")'
            singularity exec scrnaseq.sif R -e 'library(SingleR)'
            singularity exec scrnaseq.sif R -e 'library(Seurat)'
